name: Disabled - Auto PR dev -> main

on:
  # Desativado: só executa manualmente se alguém invocar
  workflow_dispatch:

permissions:
  contents: read

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Workflow desabilitado. Merge dev->main deve ser feito via PR manual."
