name: Alerta Propostas Estagnadas

on:
  schedule:
    # Executa todos os dias às 9:00 BRT (12:00 UTC)
    - cron: '0 12 * * *'
  workflow_dispatch: # Permite execução manual

jobs:
  check-stale-proposals:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Stale Proposals
        run: |
          echo "Verificando propostas estagnadas há mais de 48h..."
          
          # Faz chamada para o endpoint de verificação
          response=$(curl -s -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.SYSTEM_TOKEN }}" \
            "${{ secrets.APP_URL }}/api/proposals/stale-check")
          
          echo "Resposta da API: $response"
          
          # Verifica se a chamada foi bem-sucedida
          if echo "$response" | grep -q '"ok":true'; then
            notified=$(echo "$response" | sed -n 's/.*"notified":\([0-9]*\).*/\1/p')
            echo "✅ Verificação concluída. $notified propostas notificadas."
          else
            echo "❌ Erro na verificação de propostas estagnadas"
            echo "$response"
            exit 1
          fi

      - name: Log Execution
        if: always()
        run: |
          echo "Execução do alerta de propostas estagnadas finalizada em $(date)"
