name: Deprecated - Sync branches (disabled)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Workflow desabilitado. Use os novos auto PRs (testes->dev e dev->main)."
